import logging
import random
import sqlite3
from deck_generator import DeckGenerator
from deck_utils import setup_logging, create_llm_config, create_tts_config

# ---------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------

output_dir = "output/korean"

# Data
db_path = "data/Topik6000_Korean_Vocab/collection.anki2"

# LLM Config
system_prompt = "You are an expert Korean language teacher based in US. Your task is to help students understand and learn Korean words."

# Google TTS Config
generate_audio = True
language_code = "ko-KR"
voice_name = "ko-KR-Chirp3-HD-Achernar"

# Anki Config
anki_config = DeckGenerator.AnkiConfig(
    model_id=1234567892,
    deck_id=9876543214,
    deck_name="Korean AI"
)

# Define the structured data model for AI output
ai_schema = {
    "type": {
        "description": "Type of the word (noun, verb, etc.)",
    },
    "explanation": {
        "description": "Explanation of the word in English",
    },
    "example sentences": {
        "description": "List of example sentences using the word in English and Korean in the following format: "
                       "[Sentence in Korean] - [Setnence translation in English]. If not applicable, output an empty list.",
        "list": True,
    },
    "sino roots": {
        "description": "If applicable, provide list of sino-Korean root words in the following format: "
                       "[Hanguel] ([Hanja Character]) - [Meaning in English]. If not applicable, output an empty list.",
        "list": True,
    },
    "korean roots": {
        "description": "If applicable, provide list of native Korean root words in the following format: "
                       "[Hanguel] - [Meaning in English]. If not applicable, output an empty list.",
        "list": True,
    },
    "synonyms": {
        "description": "List of synonyms in Korean in the following format: [Hanguel] - [Meaning in English]. If not applicable, output an empty list.",
        "list": True,
    },
    "antonyms": {
        "description": "List of antonyms in Korean in the following format: [Hanguel] - [Meaning in English]. If not applicable, output an empty list.",
        "list": True,
    },
    "cultural note": {
        "description": "Cultural note about the word if it is sensible in a language class to include it. If not, output an empty string.",
    }
}

provided_fields = ["frequency"]

field_order = [
    "frequency", "word", "type", "explanation", "example sentences",
    "sino roots", "korean roots", "cultural note", "synonyms", "antonyms",
]

# ---------------------------------------------------------------------
# Functions
# ---------------------------------------------------------------------


def import_notes(cursor):
    cursor.execute("SELECT id, flds FROM notes ORDER BY id")
    # note_data = [row[0] for row in cursor.fetchall()]
    note_data = cursor.fetchall()
    notes = []
    for row in note_data:
        id = row[0]
        elem = row[1].split('\x1f')
        notes.append({
            'id': id,
            'Frequency': elem[0],
            'Word': elem[1],
            'Classification': elem[2],
            'Complexity': elem[3],
            'HanjaRef': elem[4],
            'English': elem[5],
            'Wiktionary Link': elem[6],
            'Wordreference Link': elem[7],
            'Note': elem[8],
            'Audio': elem[9][7:-1]
        })
    return notes


def main():
    setup_logging(output_dir)

    # Create configurations
    llm_config = create_llm_config(system_prompt)
    tts_config = create_tts_config(language_code, voice_name)
    schema = DeckGenerator.SchemaConfig(
        ai_schema=ai_schema,
        item_field="word",
        provided_fields=provided_fields,
        field_order=field_order
    )

    # Import data from database
    with sqlite3.connect(db_path) as conn:
        cursor = conn.cursor()
        notes = import_notes(cursor)
        logging.getLogger().info(
            f"Imported {len(notes)} notes from Anki database.")

    items = [note['Word'] for note in notes]
    provided_content = {
        "frequency": [note['Frequency'] for note in notes]
    }
    # Generate GUIDs for Anki notes. Frequency is used to ensure uniqueness.
    # Note: GUIDs are not the same as Anki note IDs.
    # Anki note IDs are generated by Anki itself.
    # GUIDs are still used internally by Anki to identify notes. This is helpful if you want to update notes later.
    ids = [f"{anki_config.deck_name.replace(' ', '')}-{freq}" for freq in provided_content["frequency"]]

    # Randomly sample n items from the notes
    # sample_size = 10
    # random_indices = random.sample(range(len(notes)), sample_size)
    # items = [items[i] for i in random_indices]
    # provided_content = {
    #     "frequency": [provided_content["frequency"][i] for i in random_indices]
    # }
    # ids = [ids[i] for i in random_indices]

    # Generate Anki deck
    deck_generator = DeckGenerator(
        schema=schema,
        llm_config=llm_config,
        tts_config=tts_config,
        anki_config=anki_config,
        gen_audio=generate_audio,
        cache_dir="cache/korean",
    )

    deck_generator.gen_deck(
        items=items,
        guids=ids,
        provided_content=provided_content,
        output_dir=output_dir,
    )


if __name__ == "__main__":
    main()
